### ISSUE TITLE
API Mismatch with current Official firmware

### ISSUE THREAD

**Issue by UberGuidoZ** [HEX0DAYS/FlipperZero-PWNDTOOLS#1]
Attempting to use the provided FAP file on the current Official firmware gives "API mismatch" error.

# [Release v2.6.0](https://github.com/HEX0DAYS/FlipperZero-PWNDTOOLS/releases/tag/2.6.0)

# Firmware
![Official](https://user-images.githubusercontent.com/57457139/196574228-cf5fcc9f-c14f-4773-93d4-349ea7dce7a5.png)

# Error
![Error](https://user-images.githubusercontent.com/57457139/196573996-e8bb7bc5-cf84-4476-916d-b6ea42e385d2.png)

**Comment by UberGuidoZ** [comment]
It's worth noting the [Unleashed FAP file](https://github.com/UberGuidoZ/Flipper/tree/main/Applications/Unleashed) (built by Nano) does not have this issue.

# Firmware
![Firmware](https://user-images.githubusercontent.com/57457139/196574520-9771ef22-ae20-4f0a-9467-f91837d6232a.png)

# No Error
![No_Error](https://user-images.githubusercontent.com/57457139/196574547-13c23b0d-2d56-499b-bc91-a6b4a4bfbce0.png)

**Comment by HEX0DAYS** [comment]
Hello @UberGuidoZ , yes, my .faps file is being compiled for cfw only, and if the .faps provided by Unleashed work with the official one, i will fork and link by my repo to this new V2 provided by Unleashed, for the next new things, i will think about the Official firmware too! Thanks @UberGuidoZ
